name = "docsmart-ai"
compatibility_date = "2024-08-13"

[env.production]
name = "docsmart-ai"

[env.preview]
name = "docsmart-ai-preview"

# Pages configuration
[[pages]]
project_name = "docsmart-ai"
build_dir = "dist"
build_command = "npm run build"

# Custom headers for security and performance
[[pages.headers]]
for = "/*"

[pages.headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[pages.headers]]
for = "/assets/*"

[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# SPA routing support
[[pages.redirects]]
from = "/*"
to = "/index.html"
status = 200
